document.addEventListener('DOMContentLoaded', () => {

  // ===== Business info (drives the printable report header) =====
  const printReportBizName = document.getElementById('printReportBizName');
  if (printReportBizName && window.business) {
    printReportBizName.textContent = `Reviews Report — ${business.name}`;
  }
  if (window.business) {
    document.title = `Graphura ReviewFlow | Reviews Management`;
  }

  // ===== Dummy Data (centralized in js/common/mock-data.js) =====
  let reviews = [...window.recentReviews];

  let activeFilter = 'all';
  let searchQuery = '';

  const reviewsList = document.getElementById('reviewsList');
  const emptyState = document.getElementById('emptyState');
  const pagination = document.getElementById('pagination');

  function starString(n) {
    return '★'.repeat(n) + '☆'.repeat(5 - n);
  }

  function sentimentLabel(sentiment) {
    if (sentiment === 'positive') return 'Excellent';
    if (sentiment === 'neutral') return 'Average';
    return 'Needs Attention';
  }

  function sentimentClass(sentiment) {
    if (sentiment === 'positive') return 'sentiment-excellent';
    if (sentiment === 'neutral') return 'sentiment-average';
    return 'sentiment-negative';
  }

  function getFilteredReviews() {
    let list = [...reviews];

    if (searchQuery) {
      const q = searchQuery.toLowerCase();
      list = list.filter((r) =>
        r.initials.toLowerCase().includes(q) ||
        r.text.toLowerCase().includes(q) ||
        sentimentLabel(r.sentiment).toLowerCase().includes(q) ||
        r.name.toLowerCase().includes(q)
      );
    }

    switch (activeFilter) {
      case '5star':
        list = list.filter((r) => r.overall === 5);
        break;
      case '4star':
        list = list.filter((r) => r.overall === 4);
        break;
      case '3star':
        list = list.filter((r) => r.overall === 3);
        break;
      case 'positive':
        list = list.filter((r) => r.sentiment === 'positive');
        break;
      case 'negative':
        list = list.filter((r) => r.sentiment === 'negative');
        break;
      case 'newest':
        list.sort((a, b) => b.date - a.date);
        break;
      case 'oldest':
        list.sort((a, b) => a.date - b.date);
        break;
      default:
        break;
    }

    return list;
  }

  function renderReviews() {
    const list = getFilteredReviews();
    reviewsList.innerHTML = '';

    if (list.length === 0) {
      emptyState.hidden = false;
      pagination.hidden = true;
      return;
    }

    emptyState.hidden = true;
    pagination.hidden = false;

    list.forEach((r, index) => {
      const card = document.createElement('div');
      card.className = 'owner-review-card reviews-page-card';
      card.style.animationDelay = `${index * 0.04}s`;
      card.dataset.id = r.id;

      card.innerHTML = `
        <div class="owner-review-top">
          <div class="reviewer-initials">${r.initials}</div>
          <div class="owner-review-meta">
            <div class="owner-review-stars">${starString(r.overall)}</div>
            <span class="owner-review-time">${r.time}</span>
          </div>
          <span class="sentiment-badge ${sentimentClass(r.sentiment)}">${sentimentLabel(r.sentiment)}</span>
        </div>
        <p class="owner-review-text">${r.text}</p>
        <div class="review-tag-row">
          ${r.ai ? '<span class="review-tag review-tag-ai">Generated by AI</span>' : ''}
          ${r.google ? '<span class="review-tag review-tag-google">Posted on Google</span>' : ''}
        </div>
        <div class="review-card-actions">
          <button type="button" class="review-action-btn" data-action="view">View</button>
          <button type="button" class="review-action-btn" data-action="reply">Reply</button>
          <button type="button" class="review-action-btn review-action-delete" data-action="delete">Delete</button>
        </div>
      `;

      reviewsList.appendChild(card);
    });
  }

  renderReviews();

  // ===== Search =====
  const searchInput = document.getElementById('searchInput');
  searchInput.addEventListener('input', () => {
    searchQuery = searchInput.value.trim();
    renderReviews();
  });

  // ===== Filter Chips =====
  const filterChips = document.querySelectorAll('.filter-chip');
  filterChips.forEach((chip) => {
    chip.addEventListener('click', () => {
      filterChips.forEach((c) => c.classList.remove('active'));
      chip.classList.add('active');
      activeFilter = chip.dataset.filter;
      renderReviews();
    });
  });

  // ===== Export PDF (real, via browser print) =====
  const exportPdfBtn = document.getElementById('exportPdfBtn');
  const printReportArea = document.getElementById('printReportArea');
  const printReportDate = document.getElementById('printReportDate');
  const printReportTableBody = document.getElementById('printReportTableBody');

  function buildPrintReport() {
    printReportDate.textContent = 'Generated on ' + new Date().toLocaleString('en-US', {
      weekday: 'long', year: 'numeric', month: 'long', day: 'numeric',
      hour: '2-digit', minute: '2-digit'
    });

    printReportTableBody.innerHTML = reviews.map((r) => `
      <tr>
        <td>${r.name}</td>
        <td>${starString(r.overall)}</td>
        <td>${sentimentLabel(r.sentiment)}</td>
        <td>${r.text}</td>
        <td>${r.time}</td>
      </tr>
    `).join('');
  }

  if (exportPdfBtn) {
    exportPdfBtn.addEventListener('click', () => {
      buildPrintReport();
      document.body.classList.add('printing-report');
      window.print();
    });
  }

  window.addEventListener('afterprint', () => {
    document.body.classList.remove('printing-report');
    showToast('PDF exported successfully.');
  });

  // ===== Pagination (UI only) =====
  const pageButtons = document.querySelectorAll('.pagination-page');
  pageButtons.forEach((btn) => {
    btn.addEventListener('click', () => {
      pageButtons.forEach((b) => b.classList.remove('active'));
      btn.classList.add('active');
    });
  });

  // ===== Modals =====
  const viewModalOverlay = document.getElementById('viewModalOverlay');
  const viewModalContent = document.getElementById('viewModalContent');
  const replyModalOverlay = document.getElementById('replyModalOverlay');
  const deleteModalOverlay = document.getElementById('deleteModalOverlay');
  const replyTextarea = document.getElementById('replyTextarea');

  let currentReviewId = null;

  function openModal(overlay) {
    overlay.classList.add('visible');
  }

  function closeModal(overlay) {
    overlay.classList.remove('visible');
  }

  function closeAllModals() {
    [viewModalOverlay, replyModalOverlay, deleteModalOverlay].forEach(closeModal);
  }

  function openViewModal(review) {
    viewModalContent.innerHTML = `
      <div class="review-detail-item"><span class="review-detail-label">Customer</span><span class="review-detail-value">${review.name}</span></div>
      <div class="review-detail-item"><span class="review-detail-label">Overall Rating</span><span class="review-detail-value">${starString(review.overall)}</span></div>
      <div class="review-detail-item"><span class="review-detail-label">Food Rating</span><span class="review-detail-value">${starString(review.food)}</span></div>
      <div class="review-detail-item"><span class="review-detail-label">Staff Rating</span><span class="review-detail-value">${starString(review.staff)}</span></div>
      <div class="review-detail-item"><span class="review-detail-label">Ambience Rating</span><span class="review-detail-value">${starString(review.ambience)}</span></div>
      <div class="review-detail-item"><span class="review-detail-label">Cleanliness</span><span class="review-detail-value">${starString(review.cleanliness)}</span></div>
      <div class="review-detail-item"><span class="review-detail-label">Recommendation</span><span class="review-detail-value">${review.recommend}</span></div>
      <div class="review-detail-item"><span class="review-detail-label">Review Date</span><span class="review-detail-value">${review.time}</span></div>
      <div class="review-detail-item"><span class="review-detail-label">Generated By AI</span><span class="review-detail-value">${review.ai ? 'Yes' : 'No'}</span></div>
      <div class="review-detail-item"><span class="review-detail-label">Google Status</span><span class="review-detail-value">${review.google ? 'Posted' : 'Not Posted'}</span></div>
      <div class="review-detail-item review-detail-full"><span class="review-detail-label">Complete Review</span><p class="review-detail-text">${review.text}</p></div>
    `;
    openModal(viewModalOverlay);
  }

  reviewsList.addEventListener('click', (e) => {
    const btn = e.target.closest('.review-action-btn');
    if (!btn) return;

    const card = e.target.closest('.owner-review-card');
    const id = Number(card.dataset.id);
    const review = reviews.find((r) => r.id === id);
    currentReviewId = id;

    const action = btn.dataset.action;

    if (action === 'view') {
      openViewModal(review);
    } else if (action === 'reply') {
      replyTextarea.value = '';
      openModal(replyModalOverlay);
    } else if (action === 'delete') {
      openModal(deleteModalOverlay);
    }
  });

  // View Modal Close
  document.getElementById('viewModalCloseBtn').addEventListener('click', () => closeModal(viewModalOverlay));

  // Reply Modal
  document.getElementById('replyCancelBtn').addEventListener('click', () => closeModal(replyModalOverlay));

  document.getElementById('replySendBtn').addEventListener('click', () => {
    const sendBtn = document.getElementById('replySendBtn');
    const originalText = sendBtn.textContent;
    sendBtn.disabled = true;
    sendBtn.textContent = 'Sending...';

    setTimeout(() => {
      sendBtn.disabled = false;
      sendBtn.textContent = originalText;
      closeModal(replyModalOverlay);
      showToast('Reply sent successfully.');
    }, 1000);
  });

  // Delete Modal
  document.getElementById('deleteCancelBtn').addEventListener('click', () => closeModal(deleteModalOverlay));

  document.getElementById('deleteConfirmBtn').addEventListener('click', () => {
    reviews = reviews.filter((r) => r.id !== currentReviewId);
    closeModal(deleteModalOverlay);
    renderReviews();
    showToast('Review removed successfully.');
  });

  // Outside click closes any modal
  [viewModalOverlay, replyModalOverlay, deleteModalOverlay].forEach((overlay) => {
    overlay.addEventListener('click', (e) => {
      if (e.target === overlay) closeModal(overlay);
    });
  });

  // ESC closes any open modal
  document.addEventListener('keydown', (e) => {
    if (e.key === 'Escape') closeAllModals();
  });

});